/**
 * AI Layer data models
 *
 * These types define the information sent to the
 * Route Context Intelligence layer and the
 * intelligence returned from it.
 */

export type GeoCoordinate = [
  longitude: number,
  latitude: number,
];

/**
 * Supported route complexity levels.
 */
export type RouteComplexity =
  | "low"
  | "medium"
  | "high";

/**
 * Visualization recommendation produced by AI.
 */
export type RecommendedVisualization =
  | "normal"
  | "reduced"
  | "minimal";

/**
 * Navigation direction associated with
 * a route segment or turn.
 */
export type RouteTurnDirection =
  | "straight"
  | "left"
  | "right";

/**
 * Context about a nearby landmark.
 */
export type LandmarkContext = {
  name: string;

  category: string;

  position: GeoCoordinate;

  distanceFromRouteMeters: number;

  distanceFromCurrentPositionMeters: number;
};

/**
 * Context about one segment of the route.
 */
export type RouteSegmentContext = {
  index: number;

  start: GeoCoordinate;

  end: GeoCoordinate;

  distanceMeters: number;

  direction: RouteTurnDirection;

  turnAngleDegrees: number;
};

/**
 * Complete geographic and navigation context
 * provided to the AI layer.
 */
export type RouteContext = {
  routeGeometry: GeoCoordinate[];

  distanceMeters: number;

  durationSeconds: number;

  turns: RouteTurnDirection[];

  segments: RouteSegmentContext[];

  nearbyLandmarks: LandmarkContext[];

  destination: {
    name: string;

    category: string;

    position: GeoCoordinate;
  };

  currentRoutePosition: GeoCoordinate | null;
};

/**
 * Intelligence generated by the AI layer.
 */
export type RouteIntelligence = {
  importantLandmarks: LandmarkContext[];

  routeComplexity: RouteComplexity;

  importantSegments: number[];

  recommendedVisualization: RecommendedVisualization;

  reason: string;
};